# Generated by Django 5.2.17 on 2026-09-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Embarcacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('matricula', models.CharField(db_index=True, help_text='Número o código único de identificación de la barcaza.', max_length=20, unique=True, verbose_name='Matrícula')),
                ('capacidad_pasajeros', models.PositiveIntegerField(verbose_name='Capacidad de pasajeros')),
                ('capacidad_vehicular', models.PositiveIntegerField(verbose_name='Capacidad vehicular')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Embarcación',
                'verbose_name_plural': 'Embarcaciones',
                'ordering': ['nombre'],
            },
        ),
    ]
