# Generated by Django 5.2.17 on 2026-10-02 21:55

import rutas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100, verbose_name='Puerto de Origen')),
                ('destino', models.CharField(max_length=100, verbose_name='Puerto de Destino')),
                ('duracion_horas', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Duración (Horas)')),
                ('precio_base', models.IntegerField(validators=[rutas.models.validar_precio_positivo], verbose_name='Precio Base ($)')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Ruta Activa?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
