# Generated by Django 5.2.17 on 2026-10-04 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salida', models.DateTimeField(verbose_name='Fecha y hora de salida')),
                ('activo', models.BooleanField(default=True, verbose_name='Salida disponible')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='rutas.ruta', verbose_name='Ruta')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['salida'],
            },
        ),
    ]
