# Generated by Django 5.2.17 on 2026-10-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0002_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='es_demostracion',
            field=models.BooleanField(default=False, verbose_name='Datos de demostración'),
        ),
    ]
