# Generated by Django 5.2.17 on 2026-10-05 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del terminal o rampa')),
                ('comuna', models.CharField(max_length=100, verbose_name='Comuna')),
                ('estado', models.CharField(max_length=120, verbose_name='Estado operativo')),
                ('marea', models.CharField(max_length=120, verbose_name='Estado de marea')),
                ('es_demostracion', models.BooleanField(default=False, verbose_name='Datos de demostración')),
            ],
            options={
                'verbose_name': 'Terminal o rampa',
                'verbose_name_plural': 'Terminales y rampas',
                'ordering': ['nombre', 'comuna'],
            },
        ),
    ]
